version: "3.8"
services:
  nsp_backend:
    container_name: poc_backend
    image: nodejs_express/poc-template:0.0.1
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=poc_database
      - PGHOST=poc_db # NAME OF THE SERVICE
    depends_on:
      - poc_db
  nsp_db:
    container_name: poc_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=poc_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
